# BBDeathChests Configuration
# Version 1.2

# Block types that can be replaced with a chest
# Refer to list of material types in Bukkit's Material enum
# (API Docs: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
chestable_blocks:
- 'WATER'                # Flowing Water
- 'STATIONARY_WATER'     # Water source blocks
- 'LAVA'                 # Flowing Lava
- 'LONG_GRASS'           # Long Grass
- 'DOUBLE_PLANT'         # 2-high plants, very tall grass, etc.
- 'YELLOW_FLOWER'        # Yellow flowers (Red isn't a material type)
- 'CROPS'                # Assorted "crops" (or make them a low block)
- 'SNOW'                 # Snow-covered block

