# BBDeathChests Configuration
# Version 1.1

# Block types that can be replaced with a chest
# Refer to list of material types in Bukkit's Material enum
# (API Docs: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html)
chestable_blocks:
- 'WATER'                # Flowing Water
- 'STATIONARY_WATER'     # Water source blocks
- 'LAVA'                 # Flowing Lava
- 'LONG_GRASS'           # Long Grass
- 'DOUBLE_PLANT'         # 2-high plants, very tall grass, etc.
- 'YELLOW_FLOWER'        # Yellow flowers (Red isn't a material type)
- 'CROPS'                # Assorted "crops" (or make them a low block)
- 'SNOW'                 # Snow-covered block (make a low block to preserve)

# Block types that are screwy: You're technically INSIDE
# these when you stand on them, so add 1 to the death
# location's Y value before checking chest-ability.
low_blocks:
- 'SOIL'                 # You're "inside" soil when standing on it.
- 'CARPET'               # We don't want to destroy carpets.
- 'STEP'                 # Assorted stone slabs
- 'STONE_SLAB2'          # Newer stone slabs
- 'WOOD_STEP'            # Assorted wood slabs
- 'PURPUR_SLAB'          # Purpur Slabs
